
services:
  movie-service:
    build:
      context: .
      dockerfile: movie/Dockerfile
    depends_on:
      - db
      - auth-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  auth-service:
    build:
      context: .
      dockerfile: auth/Dockerfile
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  db:
    image: 'postgres:16-alpine3.18'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movie-project